### ISSUE TITLE
Example settings files lost?

### ISSUE THREAD

**Issue by hanoii** [platformsh/template-drupal7-vanilla#28]
For some reason there's no `settings.php` or `settings.platformsh.php` but README references to it. This seems to have gone on the last merge.

**Comment by hanoii** [comment]
They were deleted on 4392568b145da0020d1b4217078bf24fd6eafbf2

**Comment by chadwcarlson** [comment]
@hanoii Thanks for bringing this to our attention. Fixing now.

**Comment by chadwcarlson** [comment]
Resolved by https://github.com/platformsh/template-drupal7-vanilla/pull/30
